/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echoServer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class echoServer {
    public echoServer(){
        ServerSocket mServerSocket;
        Socket mSocket;

        BufferedReader brRecv; // Recv
        PrintWriter pwSend; // Send

        try {
            mServerSocket = new ServerSocket(8888); // Server Open
            System.out.println("Java Server Start!!!");

            mSocket = mServerSocket.accept();
            System.out.println("Client Connected");

            brRecv = new BufferedReader(new InputStreamReader(mSocket.getInputStream()));
            pwSend = new PrintWriter(mSocket.getOutputStream());
            while (true) {
                String strRecvMsg = brRecv.readLine();		//클라이언트 메시지 수신
                System.out.println(strRecvMsg);

                if (strRecvMsg.equals("exit")) {
                    break;
                }

                // 클라이언트에 문자열 전송
                pwSend.println(strRecvMsg);		//메시지 echo
                pwSend.flush();
            }
            mSocket.close();
            mServerSocket.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public static void main(String[] args) {
        new echoServer();
    }
}
/*
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.InetAddress;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class echoServer { 

    public static void main(String[] args) {
        try (ServerSocket serverSocket = new ServerSocket(11111);
                Socket socket = serverSocket.accept();
                PrintWriter out = new PrintWriter(socket.getOutputStream());
                BufferedReader br = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {
 
            System.out.println("서버 대기중....");
            while (true) {
                String msg = br.readLine();
                if (msg.equalsIgnoreCase("Quit"))
                    break;
                System.out.println("클라이언트에서 보냄:[ " + msg + " ]");
                out.println(msg);
                out.flush();
            }
            System.out.println("서버종료..");
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
*/